---

- name: Configure the archive directory
  ansible.builtin.include_tasks: archive_tree.yml

- name: Configure the discos_telemetry_proxy.service
  ansible.builtin.include_tasks: telemetry_proxy.yml
